"use client";

import Head from 'next/head';
import Container from 'react-bootstrap/Container';
import Button from 'react-bootstrap/Button';
import Link from 'next/link';
import { useUser } from '@supabase/auth-helpers-react';
import { useState, useEffect } from 'react';
import PostEditForm from '@/app/components/Content/Posts/EditForm';
import usePosts from '@/lib/usePosts';
import { useRouter } from 'next/navigation';
import { Post } from '@/types/Post';

type Props = {
  params: {
    id: string;
  };
};

const PostPage = ({ params }: Props) => {
  const user = useUser();
  const router = useRouter();
  const [isEditing, setIsEditing] = useState(false);
  const [post, setPost] = useState<Post | null>(null);
  const { updatePost } = usePosts();

  useEffect(() => {
    const fetchPost = async () => {
      const response = await fetch(`/api/posts/${params.id}`);
      const data = await response.json();
      setPost(data);
    };
    fetchPost();
  }, [params.id]);

const handleSubmit = async (title: string, body: string) => {
    if (post) {
        await updatePost(post.id, title, body);
    }
};

if (!post) {
    return <div>Loading...</div>;
}

  return (
    <>
      <Head>
        <title>Posts list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Link href="/" legacyBehavior>
            <Button variant="link">{'<'}Back to all posts</Button>
          </Link>
          {isEditing ? (
            <PostEditForm post={post} saveForm={handleSubmit} />
          ) : (
            <>
              <h1>{post.title}</h1>
              <div>{post.body}</div>
              {user && user.id === post.author && (
                <Button onClick={() => setIsEditing(true)}>Edit post</Button>
              )}
            </>
          )}
        </Container>
      </main>
    </>
  );
};

export default PostPage;